grocery/cartapp/urls.py
from django.urls import path,include
from .import views as v
app_name='cart'
urlpatterns =[
    path('products',v.productt,name='product'),
    path('addtocart/<int:pk>',v.add_cart,name='addtocart1'),
    path('showcart',v.show_cart,name='showcart1'),
    path("del/<int:proid>",v.delete,name='delete1')
]

grocery/groapp/urls.py
from django.urls import path
from . import views
from django.conf import settings

urlpatterns =[
    path("/",views.home,name="home"),
    path("registration",views.registration,name="register"),
    path("user_login",views.userlogin,name="logins"),
    path("dashboard",views.user_dashboard,name="dashboards"),
    path("logout",views.logoutt,name="logouts")
]

grocery/grocery/urls.py
from django.contrib import admin
from django.urls import path,include
from groapp.views import home
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path("",home),
    path("kitchen-",include(("groapp.urls","groapp"),namespace="apps")),
    path("cartapp-",include(('cartapp.urls','cartapp'),namespace="addcart"))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

grocery/cartapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django import forms

class Product(models.Model):
    name=models.CharField(max_length=100)
    description=models.CharField(max_length=200)
    price=models.IntegerField()
    picture=models.ImageField(upload_to='images/')


    def __str__(self):
        return self.name
    
class Cart(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity=models.IntegerField(default=1)
    amount=models.IntegerField(default=0)
    total_amt=models.IntegerField(default=0)

    def total_cost(self):
        return self.quantity*self.product.price
    
class CartItem(forms.ModelForm):
    class Meta:
        model=Cart
        fields='__all__'

grocery/groapp/models.py
from django.db import models
from django.contrib.auth.models import User

class Registration(models.Model):
    name=models.CharField(max_length=60)
    city=models.CharField(max_length=30)
    mobile_no=models.CharField(max_length=10)
    user=models.ForeignKey(User,on_delete=models.CASCADE)

grocery/groapp/forms.py
from .models import *
from django import forms
from django.contrib.auth.forms import UserCreationForm

class RegistrationForm(forms.ModelForm):
    class Meta:
        model= Registration
        fields=['user','name','mobile_no','city']


class LoginForm(forms.Form):
    username=forms.CharField(max_length=10,widget=forms.TextInput(attrs={'class':'form-control'}))
    password=forms.CharField(max_length=10,widget=forms.PasswordInput(attrs={'class':'form-control'}))

grocery/cartapp/views.py
from django.shortcuts import render,redirect,HttpResponse
from .models import *

def productt(request):
    obj=Product.objects.all()
    d={'product':obj}
    return render(request,'products.html',d)

    
def add_cart(request,pk):
    user_id=request.session.get("id")
    user=request.user
    if request.method=='GET':
        product=Product.objects.get(id=pk)
        Cart(user=user,product=product).save()
        return redirect("/cartapp-products")

def show_cart(request):
    ids=request.session.get("id")
    obj=Cart.objects.filter(user=ids)
    amount=0
    value=0
    for p in obj:
        value=p.quantity*p.product.price
        amount=value+amount
        total_amount= amount + 45
        d={'data':obj,'total_amount':total_amount,'amount':amount}
        return render(request,'carts.html',d)
    
def delete(request,proid):
    obj=Cart.objects.get(id=proid)
    obj.delete()
    return redirect("/cartapp-showcart")


def plus_cart(request,pid):
   if request.method=='GET': 
    c=Cart.objects.get(id=pid)
    c.quantity +=1
    c.save()
    user=request.user
    cart=Cart.objects.filter(user=user)
    for i in cart:
        amount=0
        value= i.quantity*i.product.price
        amount=amount+ value
        total_amount=amount + 45
        data={"quantity":c.quantity,"amount":c.amount,"total_amount":c.total_amount}
        return redirect("/cartapp-showcart")
    
def plus_cart(request,pid):
   if request.method=='GET': 
    c=Cart.objects.get(id=pid)
    c.quantity -=1
    c.save()
    user=request.user
    cart=Cart.objects.filter(user=user)
    for i in cart:
        amount=0
        value= i.quantity*i.product.price
        amount=amount+ value
        total_amount=amount + 45
        data={"quantity":c.quantity,"amount":c.amount,"total_amount":c.total_amount}
        return redirect("/cartapp-showcart")

grocery/groapp/views.py
from django.shortcuts import render,redirect,HttpResponse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate,login,logout 
from .models import *
from .forms import *

def home(request):
    return render(request,'home.html')

def registration(request):
    if request.method=='POST':
        obj= UserCreationForm(request.POST)
        obj.save()
        return redirect("/kitchen-user_login")
    else:
        d={'form':UserCreationForm}
        return render(request,'register.html',d)

def userlogin(request):
    if request.method=='POST':
        uname=request.POST.get("username")
        passwd=request.POST.get("password")
        users=authenticate(request,username=uname,password=passwd)
        if users is not None:
            request.session["id"]=users.id
            print(request.session.get("id"))
            login(request,users)
            return redirect("/kitchen-dashboard")
        else:
            d={'form':LoginForm}
            return render(request,'login.html',d)
    else:
            d={'form':LoginForm}
            return render(request,'login.html',d)

def user_dashboard(request):
  try:
    if request.method=='POST':
        user_id=request.session.get("id")
        obj_user=User.objects.get(id=user_id)
        obj=RegistrationForm(request.POST)
        data=obj.save(commit=False)
        data.user=obj_user
        data.save()
        return redirect("/kitchen-dashboard")
    else:
        d={'forms':RegistrationForm}
        return render(request,'dashboard.html',d)
  except User.DoesNotExist:
      return False
      


def logoutt(request):
    logout(request)
    return redirect("/")

grocery/cartapp/templates/carts.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Order Your Coffee!</title>
    <link rel="stylesheet" href="{%static 'css/main.css' %}">
    <link rel="stylesheet" href="{%static 'css/my.css' %}">
</head>
<body style="background-color: rgba(34, 2, 2, 0.87);">
    {%include 'navbar.html'%}
    <div class="container my-5">
        <div class="row">
            {% if data %}
            <h1 class="text-center mb-5">Shopping Cart</h1>
            <div class="col-sm-8">
                <div class="card">
                    <div class="card-body">
                        <h3>Cart</h3>
                        {% for i in data %}
                        <div class="row">
                            <div class="col-sm-3 text-center align-self-center"><img src="{{i.product.picture.url}}" alt="" class="img-fluid img-thumbnail shadow-sm" height="150" width="150"></div>
                            <div class="col-sm-9">
                                <div><h5>{{i.product.title}}</h5>
                                    <p class="mb-2 text-muted small">{{i.product.description}}</p>
                                    <div class="my-3">
                                        <label for="quantity" >Quantity</label>
                                        <a href="#" name="pid" class="minus-cart btn"  pid="{{i.product.id}}"><i class="fas fa-minus-square fa-lg ">+</i>
                                        </a>
                                        <span id="quantity">{{i.quantity}}</span>
                                        <a href="#" name='pid' class="plus-cart btn" pid="{{i.product.id}}"><i class="fas fa-plus-square fa-lg">-</i></a>
                                    </div>
                                    <div class="d-flex justify-content-between">
                                     <a href="{%url 'addcart:delete1' i.id %}" class="remove-cart btn btn-sm btn-secondary mr-3" name="proid"   proid="{{i.product.id}}">Remove</a>
                                        
                                        
                            
                                    </div>
                                </div>
                            </div> 
                        </div>
                        <hr class="text-muted">
                        {% endfor %}
                    </div>
                </div>
            </div>
            
            <div class="col-sm-4">
                <div class="card">
                    <div class="card-body">
                        <h3>Total Amount Of</h3>
                        <ul class="list-group">
                            <li class="list-group item d-flex justify-content-between align-item-center border-0 px-0 pb-0">Amount <span id="amount" >Rs.{{amount}}</span></li>
                            <li class="list-group item d-flex justify-content-between align-item-center border-0 px-0">Shipping <span>Rs.45</span></li>
                            <li class="list-group item d-flex justify-content-between align-item-center border-0 px-0 nb-3">
                                <div> 
                                    <strong>Total</strong> <small>(Including GST)</small>
                                </div>
                                <span id="totalamount"><strong>Rs.{{total_amount}}</strong></span>
                            </li>
                        </ul>
                        <div class="d-grid"><a href="#" class="btn btn-primary">Place Order</a></div>
                    </div>
                </div>
            </div>
            {% else %}
            <h1 class="text-center nb-5"> Cart Is Empty</h1>
           {% endif %}
        </div>
    </div>


    <link rel="stylesheet" href="{%static 'js/main.js' %}">
</body>
</html>

grocery/cartapp/templates/products.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Order Your Coffee!</title>
    <link rel="stylesheet" href="{%static 'css/main.css' %}">
    <link rel="stylesheet" href="{%static 'css/my.css' %}">
</head>
<body style="background-color: rgba(34, 2, 2, 0.87);">
    {%include 'navbar.html'%}
    <h2>Products</h2>
    <div class="product-list">
         {%for i in product %}
            <div class="col-md-3 mb-3">
              <div class="card">
                <img src="{{i.picture.url}}" class="card-img-top" alt="{{i.name}}">
                 <div class="card-body">
                    <h5 class="card-title">{{ i.name }}</h5>
                    <p class="card-text">{{ i.description }}</p>
                    <p class="card-text">Price: Rs.{{ i.price }}</p>
                    <button><a href="{% url 'addcart:addtocart1' i.id %}">Add Cart</a></button>
                 </div>
              </div>
            </div>
            {%empty%}
            <p>No Products Found</p>
         {%endfor%}
    </div>
    <link rel="stylesheet" href="{%static 'js/main.js' %}">
</body>
</html>

grocery/groapp/templates/dashboard.html
<!doctype html>
<html lang="en">
    {%  load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/my.css' %}"> 
    <link rel="stylesheet" href="{% static 'js/main.js' %}">
    <title>Apna Kitchen</title>
  </head>
<body>
  <nav class="navbar navbar-expand-lg ">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Apna Kitchen</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarScroll">
        <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;"> 
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">HOME</a>
          </li>
      {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'apps:dashboards' %}">DASHBOARD</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'apps:logouts' %}">LOGOUT</a>
          </li>
          <li><h4>Welcome {{user}} </h4 ></li>
           
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'addcart:product' %}">PRODUCTS</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'addcart:showcart1' %}">SHOWCART</a>
          </li>
     {%else%}
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'apps:register' %}">REGISTER</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'apps:logins' %}">LOGIN</a>
          </li>
      {%endif%}
        </ul>
      </div>
    </div>
  </nav>
    
    <form method="post">
        {%csrf_token%}
        <table border="1px">
            {{forms.as_table}}
            <tr>
                 <td><input type="submit" value="submit"></td>
                 <td><input type="reset" value="Reset"></td>
            </tr>
        </table>
    </form>
    
 
  </body>
</html>

grocery/groapp/templates/home.html
<!doctype html>
<html lang="en">
    {%  load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/my.css' %}"> 
    <link rel="stylesheet" href="{% static 'js/main.js' %}">
    <title>Apna Kitchen</title>
  </head>
  <body>
    {% include 'navbar.html' %}

    
 
  </body>
</html>

grocery/groapp/templates/login.html
<!doctype html>
<html lang="en">
    {%  load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/my.css' %}">
    <link rel="stylesheet" href="{% static 'js/main.js' %}">
    <title>Apna Kitchen</title>
  </head>
  <body>
    {% include 'navbar.html' %}

    <div class="loginbar">
         <form  method="post">
            {%csrf_token%}
            <table>
                {{form}}
                <tr><td><input type="submit" value="Login"></td></tr>
            </table>
         </form>
    </div>
  </body>
  </html>

grocery/groapp/templates/navbar.html
<!doctype html>
<html lang="en">
    {%  load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
   <link rel="stylesheet" href="{% static 'css/my.css' %}">
    <link rel="stylesheet" href="{% static 'js/main.js' %}">
    <title>Apna Kitchen</title>
  </head>
<body>
  <nav class="navbar navbar-expand-lg ">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Apna Kitchen</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarScroll">
        <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;"> 
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">HOME</a>
          </li>
      {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'apps:dashboards' %}">DASHBOARD</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'apps:logouts' %}">LOGOUT</a>
          </li>
          <li><h4>Welcome {{user}} </h4 ></li>
           
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'addcart:product' %}">PRODUCTS</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'addcart:showcart1' %}">SHOWCART</a>
          </li>
     {%else%}
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'apps:register' %}">REGISTER</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'apps:logins' %}">LOGIN</a>
          </li>
      {%endif%}
        </ul>
      </div>
    </div>
  </nav>
</body>
</html>

grocery/groapp/templates/register.html
<!doctype html>
<html lang="en">
    {%  load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/my.css' %}">
    <link rel="stylesheet" href="{% static 'js/main.js' %}">
    <title>Apna Kitchen</title>
  </head>
  <body>
    {% include 'navbar.html' %}
    <div>   
      <form  method="post">
         {%csrf_token%}
         <table>
            {%for i in form%}
              {{i.label_tag}}{{i}} <br><br>
            {%endfor%}
            <tr>
              <td><input type="submit" value="Register"></td>
            </tr>
         </table>
      </form>
      </div>
    
 
  </body>
</html>